// priority: 99
events.listen('recipes', event => {
    event.recipes.mekanism.enriching(item.of('thermal:silver_dust', 2), '#forge:ores/silver').id('avrd:ore/silver/dust')
    event.recipes.mekanism.crushing(item.of('thermal:silver_dust'), '#forge:ingots/silver').id('avrd:ingot/silver/dust')
    event.recipes.mekanism.crushing(item.of('emendatusenigmatica:sulfur_dust',1),'#forge:gems/sulfur').id('avrd:gem/sulfur')
    event.recipes.mekanism.enriching(item.of('thermal:nickel_dust', 2), '#forge:ores/nickel').id('avrd:ore/nickel/dust')
    event.recipes.mekanism.crushing(item.of('thermal:nickel_dust'), '#forge:ingots/nickel').id('avrd:ingot/nickel/dust')

    event.recipes.mekanism.enriching(item.of('emendatusenigmatica:zinc_dust', 2), '#forge:ores/zinc').id('avrd:ore/zinc/dust')
    event.recipes.mekanism.crushing(item.of('emendatusenigmatica:zinc_dust'),'#forge:ingots/zinc').id('avrd:ingot/zinc/dust')
    event.remove({id:'mekanism:steel_casing'})
    event.shaped(item.of('mekanism:steel_casing',1),['SPS','PCP','SPS'],{S:'#forge:ingots/steel',P:'#forge:plastic',C:'create:brass_casing'}).id('avrd:meka/casing')
    event.remove({id:'thermal:machine_frame'})
    event.shaped(item.of('thermal:machine_frame',1),['IPI','PCP','IPI'],{I:'#forge:ingots/iron',P:'#forge:plastic',C:'create:andesite_casing'}).id('avrd:thermal/frame')
    event.remove({id:'mekanism:crusher'})
    event.shaped(item.of('mekanism:crusher',1),['RCR','SBM','RCR'],{S:'mekanism:steel_casing',M:'thermal:machine_pulverizer',R:'#forge:dusts/redstone',C:'#forge:circuits/basic',B:'minecraft:lava_bucket'}).id('avrd:meka/crusher/starter')
    event.remove({id:'mekanism:energized_smelter'})
    event.shaped(item.of('mekanism:energized_smelter',1),['RCR','SBM','RCR'],{S:'mekanism:steel_casing',M:'thermal:machine_furnace',R:'#forge:dusts/redstone',C:'#forge:circuits/basic',B:'#forge:glass'}).id('avrd:meka/smelter/starter')
    event.remove({id:'mekanism:osmium_compressor'})
    event.shaped(item.of('mekanism:osmium_compressor',1),['RCR','SBM','RCR'],{S:'mekanism:steel_casing',M:'thermal:machine_smelter',R:'#forge:alloys/advanced',C:'#forge:circuits/advanced',B:'minecraft:bucket'}).id('avrd:meka/compressor/starter')
    event.remove({id:'mekanism:enrichment_chamber'})
    event.shaped(item.of('mekanism:enrichment_chamber',1),['RCR','SBM','RCR'],{S:'mekanism:steel_casing',M:'thermal:device_water_gen',R:'#forge:dusts/redstone',C:'#forge:circuits/basic',B:'#forge:ingots/iron'}).id('avrd:meka/enrichment/starter')
    event.remove({id:'rftoolsbuilder:builder'})
    event.shaped(item.of('rftoolsbuilder:builder',1),['CEC','IDI','CIC'],{C:'#forge:circuits/ultimate',E:'#forge:ender_pearls',I:'#forge:ingots/draconium',D:Item.of('industrialforegoing:infinity_drill', '{CanCharge:1b,Special:0b,Selected:"POOR",Energy:0L,Fluid:{FluidName:"biofuel",Amount:0}}').ignoreNBT()})
})